### ISSUE TITLE
گزارش باگ و مشکل

### ISSUE THREAD

**Issue by jamali-amirhossein** [mahdiMGF2/botmirzapanel#10]
باسلام و احترام خدمت برنامه نویس محترم.
پنل: ثنایی آخرید نسخه
کانفیگ: Vmess و tls-tcp
نوع ارتباط: تانل دکومودور
شرح باگ: وقتی گزینه ارسال کانفیگ دستی را فعال و گزینه لینک سابکریپشن را غیر فعال میکنیم و مشتری سرویس خریداری میکند کد کانفیگ برای مشتری ارسال نمیگردد. کد کانفیگ در اکانت تست نیز ارسال نمی شود. یه موضوع جالب اینه وقتی نوع نام کاربری را به متن دلخواه+رندوم تغییر میدیم و متن دلخواه‌مون رو وارد مکنیم، چند دکمه تحت عنوان های نوع پروتکل ، نوع flow ظاهر می شوند که با برگشت به منو قبل و مجدد بازگشت این دکمه ها غیب میشن.
ممنون میشیم بررسی بفرمایید.
سپاس و درود فراوان

**Comment by mahdiMGF2** [comment]
سلام 

بخش اول ارسال نشدن کانفیگ : 
با توجه به این که ربات کانفیگ را از لینک ساب پنل ثنایی میخواند باید لینک ساب پنل حتما روشن باشد تا بتوانید کانفیگ ها در ربات دریافت کنید 
در ضمن تنظیمات باید دیفالت باشد اگر تنظیمات لینک ساب پنل را بخواهید تغییر بدید باید از ربات هم اطلاعات را تغییر دهید.


بخش دوم بررسی خواهد شد.
