### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by NaderKochike** [mahdiMGF2/botmirzapanel#13]
سلام
پنلم سنایی هست و وقتی دستور نصب رو میزنم و دامنه رو وارد میکنم
وقتی میخواد apache2 فعال بشه ارور password is not correct مواجه میشم؟
دلیلش چی میتونه باشه؟

**Comment by Bee-7** [comment]
> سلام پنلم سنایی هست و وقتی دستور نصب رو میزنم و دامنه رو وارد میکنم وقتی میخواد apache2 فعال بشه ارور password is not correct مواجه میشم؟ دلیلش چی میتونه باشه؟

ورژن سیستم عامل ubuntu 22.04  نیست چک کن
