### ISSUE TITLE
بک آپ

### ISSUE THREAD

**Issue by Hajiyor** [mahdiMGF2/botmirzapanel#14]
سلام چطوری میتونم از ربات بک آپ بگیرم و به یه سرور دیگه انتقال بدم؟

**Comment by mahdiMGF2** [comment]
سلام 
از داخل phpmyadmin دیتابیس را انتخاب و خروجی بگیرید سپس داخل سرور جدید در phpmyadmin دیتابیس را ایمپورت کنید
