### ISSUE TITLE
هنگ کردن ربات

### ISSUE THREAD

**Issue by Bee-7** [mahdiMGF2/botmirzapanel#18]
سلام همین امروز ربات رو نصب کردم و یک پنل مرزبان رو بهش اضافه کردم وضعیت اتصال درست هست تعداد یوزر ها و مقدار مصرف ترافیک کل رو درست نشون میده ولی به هنگام ساختن اکانت جدید ربات هنگ میکنه و ریسپانسی نداره ولی توی پنل مثلا 7 8 تا یوزر میسازه مشکل از چی میتونه باشه ؟

**Comment by mahdiMGF2** [comment]
سلام فایل لاگ به ایدی ربات @mahdisupportbot ارسال کنید

**Comment by Bee-7** [comment]
سرور رو ریبیلد کردم لاگ رو الان ندارم و کاری که کردم این بود :
از قسمت ریلیز ورژن پایین تر رو دانلود کردم و به صورت لوکال ربات رو نصب کردم وقتی که ربات به درستی کار مبکرد بعد آپدیت کردم به ورژن آخر
یه سرور دیگه ران کردم الان دوباره مستقیم از لینک گیتهاب نصب کردم مشکلی نبود درست کار میکرد
خیلی ممنونم بابت همه زحمات و پیگیری هاتون کارتون حرف نداره
