### ISSUE TITLE
Stop Working

### ISSUE THREAD

**Issue by ataafrodit** [mahdiMGF2/botmirzapanel#20]
سلام بعضی وقتا شده رباتم دیگه جواب کامند هارو نده
انگار که اصلا نصب نیست
سرورم ری استارت میکنم بازم فیکس نمیشه
ادرس phpmyadmin در دسترسه و اوکیه ولی ربات کار نمیکنه

**Comment by mahdiMGF2** [comment]
سلام مشکل از سرورتون هست
