### ISSUE TITLE
ارسال لینک کانفیگ پنل

### ISSUE THREAD

**Issue by Mahdisayiar** [mahdiMGF2/botmirzapanel#23]
من تو ربات لینک ساب رو خاموش کردم و فقط ارسال کانفیگ دستی رو روشن کردم ولی ربات بازم لینک ساب میفرسته یا قسمت لینک رو خالی ارسال میکنه
پنلم ثنایی هستش و اتصال ربات به پنل اوکیه
چیکارش کنم که دقیقا لینک کانفیگ رو برای مشتری ارسال کنه تا خودش داخل v2ray واردش کنه

**Comment by ramin9659** [comment]
دقیقا همین مشکل رو دارم

**Comment by mahdiMGF2** [comment]
سلام این مطالعه کنید 
https://t.me/mirzapanel/462
https://t.me/mirzapanel/397
