### ISSUE TITLE
باگ لینک ساب پنل ثنایی

### ISSUE THREAD

**Issue by xpersian** [mahdiMGF2/botmirzapanel#41]
تو نسخه ۴.۱۰.۴ پورت و path وجود نداره و همون ادرس پنل وارد میشه که مجبوریم بعد کانفیگ یکبار هم از phpmyadmin تغیر بدیم

**Comment by mahdiMGF2** [comment]
سلام خوب داخل ربات موقع وارد کردن لینک محدودیتی وجود نداره همون آدرس خالی میتونید بزنید

**Comment by xpersian** [comment]
نه از داخل ربات نمیشه خودتون امتحان کنید
وقتیکه پنل رو اضافه میکنید فقط لینک و پورت پنل رو میخواد و از اونجایی که بصورت پیشفرض پورت و سابلینک سابسکریپشن فرق داره و اضافه ش نمیکنه مجبورا باید از دیتا بیس اضافه کرد و تو ربات جایی برای تعیین اون وجود نداره
مثلاً بصورت پیشفرض آدرس و پورت ربات اینه
Example:2053
اما لینک پیشفرض ساب اینه
Example:2096/sub
و تو ربات جایی برای تعریف این نیست 
و لطفاً اینو هم برای پنل ثنایی و علیرضا تعریف کنید که لینک سابسکریپشن JSON رو هم بگیرن اونم بصورت پیشفرض اینه
Example:2096/json
که  درحال حاضر تو ربات حتی با تغییر دیتا بیس نمیشه همزمان هردو لینک ساب عادی و json رو به کاربران داد
