### ISSUE TITLE
باگ درگاه ارزی ریالی دیجی سواپ

### ISSUE THREAD

**Issue by xpersian** [mahdiMGF2/botmirzapanel#43]
هیچ تنظیمی برای درگاه ارزی ریالی دیجی سواپ وجود نداره و عیر قابل استفاده است

**Comment by mahdiMGF2** [comment]
سلام  دیجی سواپ نیست سواپینو هست متن اشتباه خورده است
سواپینو فعلا که کار نمیکنه اما اگر دوباره فعال شد فقط باید از بخش nowpayment api رو تنظیم کنید
